### PR TITLE
Removed examples and corresponding libva submodule dependency.

### PR DESCRIPTION
**Pull request by badiozam**
The examples and the submodule libva are not used and contribute to build time. I'd like to remove them. I'm building a shining_software sandbox right now with this branch to verify.

### CODE REVIEW

**Comment by PhuongCodingModel** [comment]
Probably also want to remove: https://github.com/braincorp/beignet/blob/8011805f187766ed7fef1ba30761ca56c519fcae/CMakeLists.txt#L285-L315

**Comment by badiozam** [comment]
@PnnBrain good idea. Done!

**Comment by badiozam** [comment]
I was able to build a sandbox with this branch as the dependency (the CMakeList.txt rule I removed above is by default off so it didn't affect the building). All to say I think we can merge this. What do you guys think?

**Comment by PhuongCodingModel** [comment]
Sounds good

**Review by PhuongCodingModel — APPROVED** [review]

**Pull request merged**
